[package]
name = "site"
version = "0.1.0-alpha"
description = "A web server with Axum and Askama"
readme = "../../README.md"
repository = "https://github.com/rrvsh/tools"
edition = "2024"
license = "MIT"
keywords = ["web"]
categories = ["site"]

[dependencies]
askama = "0.15.1"
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"] }

[lints.clippy]
correctness = "deny"
suspicious = "deny"
complexity = "deny"
perf = "deny"
style = "deny"
pedantic = "deny"
cargo = "deny"
nursery = "deny"
