name: Build container image and push to container registry

on:
  push:
    branches:
      - prime
  repository_dispatch:

jobs:
  build-and-push:
    strategy:
      matrix:
        arch: [amd64, arm64]
        image: [site]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Checkout content repository
        if: ${{ matrix.image == 'site' }}
        timeout-minutes: 5
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: rrvsh/site-content
          path: content
          persist-credentials: false

      - name: Install Nix
        timeout-minutes: 5
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
        with:
          # lets us bypass the rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix dependencies
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Login to GitHub Container Registry
        timeout-minutes: 5
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load container images
        timeout-minutes: 5
        run: |
          IMAGE_PATH="$(
            nix build \
              ".#packages.${{ matrix.arch == 'amd64' && 'x86_64' || 'aarch64' }}-linux.${{ matrix.image }}-image" \
              --print-out-paths ${{ matrix.image == 'site' && '--override-input site-content ./content' || '' }}
          )"
          nix develop -c docker load -i "$IMAGE_PATH"

      - name: Publish container images
        timeout-minutes: 5
        run: |
          nix develop -c docker tag ${{ matrix.image }}:latest ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}-${{ matrix.arch }}
          nix develop -c docker tag ${{ matrix.image }}:latest ghcr.io/rrvsh/${{ matrix.image }}:latest-${{ matrix.arch }}
          nix develop -c docker push ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}-${{ matrix.arch }}
          nix develop -c docker push ghcr.io/rrvsh/${{ matrix.image }}:latest-${{ matrix.arch }}


  publish-multi-arch:
    needs: build-and-push
    strategy:
      matrix:
        image: [site]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        timeout-minutes: 5
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish multi-arch manifest
        timeout-minutes: 5
        run: |
          docker manifest create ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }} \
            ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}-amd64 \
            ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}-arm64
          docker manifest annotate ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }} ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}-amd64 --arch amd64
          docker manifest annotate ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }} ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}-arm64 --arch arm64
          docker manifest push ghcr.io/rrvsh/${{ matrix.image }}:${{ github.sha }}
          docker manifest create ghcr.io/rrvsh/${{ matrix.image }}:latest \
            ghcr.io/rrvsh/${{ matrix.image }}:latest-amd64 \
            ghcr.io/rrvsh/${{ matrix.image }}:latest-arm64
          docker manifest annotate ghcr.io/rrvsh/${{ matrix.image }}:latest ghcr.io/rrvsh/${{ matrix.image }}:latest-amd64 --arch amd64
          docker manifest annotate ghcr.io/rrvsh/${{ matrix.image }}:latest ghcr.io/rrvsh/${{ matrix.image }}:latest-arm64 --arch arm64
          docker manifest push ghcr.io/rrvsh/${{ matrix.image }}:latest

  redeploy-ecs-service:
    needs: publish-multi-arch
    strategy:
      matrix:
        image: [site]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Install Nix
        timeout-minutes: 5
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
        with:
          # lets us bypass the rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix dependencies
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Login to AWS
        timeout-minutes: 5
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Force redeploy of ECS service
        timeout-minutes: 5
        run: |
          nix develop -c aws ecs update-service \
            --cluster ${{ matrix.image }} \
            --service ${{ matrix.image }} \
            --force-new-deployment
