name: Build container image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Check out code
        timeout-minutes: 1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Install Nix
        timeout-minutes: 5
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
        with:
          # lets us bypass the rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            
      - name: Cache dependencies
        timeout-minutes: 5
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39

      - name: Build container image
        timeout-minutes: 5
        run: |
          nix build .#packages.x86_64-linux.rrvsh-image
