name: Build container image

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out code
        timeout-minutes: 1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Install Nix
        timeout-minutes: 5
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
        with:
          # lets us bypass the rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            
      - name: Cache dependencies
        timeout-minutes: 5
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39

      - name: Authenticate to GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        timeout-minutes: 5
        with:
          service_account: 'infra-ci@rrvsh-production.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/1096616770660/locations/global/workloadIdentityPools/github-actions/providers/tools'

      - name: Build and push container image
        timeout-minutes: 5
        env:
          IMAGE: asia-southeast1-docker.pkg.dev/rrvsh-production/tools/rrvsh
          DEFAULT_BRANCH: prime
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

          OUT_PATH=$(nix build .#packages.x86_64-linux.rrvsh-image --print-out-paths)
          docker load < "$OUT_PATH"

          docker tag rrvsh:latest ${IMAGE}:${{ github.sha }}
          docker push ${IMAGE}:${{ github.sha }}

          if [ "$REF" = "$DEFAULT_BRANCH" ]; then
            docker tag rrvsh:latest ${IMAGE}:latest
            docker push ${IMAGE}:latest
          fi
