name: Run checks and tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
        with:
          # lets us bypass the rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Cache dependencies
        timeout-minutes: 5
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39

      - name: Run all checks
        run: |
          nix develop -c just check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needed for zizmor
