name: Check for changes to docs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'release/**'

jobs:
  ensure_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Get all changed markdown files
        timeout-minutes: 5
        id: changed-markdown-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            **/*.md

      - name: Fail if no change to docs
        timeout-minutes: 5
        if: steps.changed-markdown-files.outputs.any_changed == 'false'
        run: exit 1
